import React from 'react';
import { Link } from 'react-router-dom';
import {
  FileText,
  Layers,
  Minimize2,
  Scissors,
  BookOpen,
  CheckCircle2,
  ShieldCheck,
  Zap,
  HelpCircle,
  Sparkles,
  ArrowRight,
  Edit3,
  Scan,
  Globe,
  Smartphone,
  Cpu,
  Lock,
  Award,
  RefreshCw
} from 'lucide-react';

export const PDFToWordSEOContent: React.FC = () => {
  const faqs = [
    {
      question: 'Is it safe to convert PDF to Word with SmartPDF AI?',
      answer:
        'Yes, completely safe. SmartPDF AI processes your PDF documents locally using browser-native WebAssembly algorithms or secure serverless pipelines. Your files are never stored or used to train public models, guaranteeing 100% document privacy.',
    },
    {
      question: 'Will my converted Word document keep the original formatting and layout?',
      answer:
        'Yes! SmartPDF AI uses advanced structural layout recognition to preserve original fonts, headings, tables, bulleted lists, margins, embedded graphics, and column alignments when converting to Microsoft Word (.docx).',
    },
    {
      question: 'Can SmartPDF AI convert scanned PDF documents into editable Word text?',
      answer:
        'Yes. With our built-in Optical Character Recognition (OCR) engine enabled, SmartPDF AI automatically extracts text from scanned image PDFs, photo documents, and image-only pages, transforming them into fully editable Word text.',
    },
    {
      question: 'Is there a limit on file size or daily document conversions?',
      answer:
        'No. SmartPDF AI allows unlimited PDF to Word conversions with no restrictive file size limits, daily conversion caps, or hidden paywalls.',
    },
    {
      question: 'Can I convert multiple PDF files to Word simultaneously in batch mode?',
      answer:
        'Yes! You can upload multiple PDF documents at once and batch convert them all to Word (.docx) files. You can download individual converted DOCX files or grab all converted documents in a convenient ZIP archive.',
    },
    {
      question: 'Does SmartPDF AI add watermarks to converted Word files?',
      answer:
        'Never. All converted Word (.docx) documents generated by SmartPDF AI are completely clean, watermark-free, and ready for immediate editing or publication.',
    },
    {
      question: 'Do I need Microsoft Office installed on my computer to convert files?',
      answer:
        'No software installation is required. SmartPDF AI generates native Microsoft Word (.docx) files directly in your web browser, which can be opened in Microsoft Word, Google Docs, LibreOffice, or Pages.',
    },
    {
      question: 'Does SmartPDF AI work on mobile devices like iPhone and Android?',
      answer:
        'Yes! SmartPDF AI is fully responsive and optimized to run seamlessly across iOS, Android, iPadOS, macOS, Windows, and Linux browsers.',
    },
    {
      question: 'What is the difference between Local Browser Engine and Cloud OCR Engine?',
      answer:
        'The Local Browser Engine converts standard vector text PDFs inside your browser with maximum privacy and speed. The Cloud OCR Engine handles complex scanned images, degraded scans, and non-selectable text PDFs using advanced optical recognition.',
    },
  ];

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  };

  return (
    <div className="mt-16 border-t border-slate-800/80 pt-16 space-y-16 text-slate-300">
      {/* FAQ Schema Script */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      {/* Section 1: What is PDF to Word Conversion? (300+ Words) */}
      <section className="bg-[#141417]/80 border border-slate-800/80 rounded-3xl p-6 sm:p-10 shadow-xl space-y-6">
        <div className="flex items-center space-x-3">
          <div className="p-2.5 rounded-xl bg-red-500/10 text-red-400 border border-red-500/20">
            <FileText className="w-6 h-6" />
          </div>
          <div>
            <span className="text-xs font-semibold text-red-400 uppercase tracking-wider">
              Comprehensive Guide
            </span>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-white">
              What is PDF to Word Conversion?
            </h2>
          </div>
        </div>

        <div className="space-y-4 text-sm sm:text-base leading-relaxed text-slate-300">
          <p>
            <strong>PDF to Word Conversion</strong> is the complex document transformation process of parsing a read-only Portable Document Format (PDF) file and accurately reconstructing its text content, typographic hierarchy, image assets, table structures, and page geometry into a fully editable Microsoft Word (.docx) document. While PDF files excel at maintaining universal visual consistency across different devices and operating systems, their fixed-layout architecture makes editing text, adjusting paragraphs, or modifying formatting notoriously difficult without specialized software.
          </p>

          <p>
            Converting a PDF into a Word document breaks down these read-only barriers. During conversion, advanced layout analysis algorithms examine the raw PDF stream data—identifying body text paragraphs, heading styles, column grids, bulleted lists, embedded table cells, font families, and raster images. The converter then translates these vector streams into native OpenXML (.docx) elements. For scanned paper documents or image-only PDFs, Optical Character Recognition (OCR) technology scans pixel raster data, identifies letter glyphs and characters, and synthesizes editable typography into the generated document structure.
          </p>

          <p>
            SmartPDF AI redefines PDF to Word conversion by offering dual processing engines: a privacy-centric, 100% in-browser WebAssembly converter for instant local document processing, alongside an intelligent AI-powered OCR engine for handling complex scanned PDFs and multi-column document layouts. Whether you need to update an old contract, edit a research paper, repurpose resume text, or revise corporate documentation, SmartPDF AI delivers pixel-accurate Word files while keeping your private data secure.
          </p>
        </div>
      </section>

      {/* Section 2: How to Convert PDF to Word (Step-by-Step Guide) */}
      <section className="space-y-8">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <span className="text-xs font-bold text-red-400 uppercase tracking-wider">
            Quick Tutorial
          </span>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-white">
            How to Convert PDF to Word Online Step-by-Step
          </h2>
          <p className="text-sm text-slate-400">
            Transform your PDF documents into editable DOCX files in four simple steps.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {[
            {
              step: '01',
              title: 'Upload PDF Files',
              description:
                'Drag and drop your PDF files into the converter area or click "Select PDF files" to upload single or multiple documents.',
            },
            {
              step: '02',
              title: 'Configure Engine & OCR',
              description:
                'Choose Auto mode, or explicitly toggle Optical Character Recognition (OCR) for scanned image documents.',
            },
            {
              step: '03',
              title: 'Click Convert to Word',
              description:
                'Press "Convert All to Word" to start processing. Watch real-time progress indicators as pages convert.',
            },
            {
              step: '04',
              title: 'Download DOCX Files',
              description:
                'Download your individual converted Word (.docx) documents or grab all files at once in a convenient ZIP archive.',
            },
          ].map((item) => (
            <div
              key={item.step}
              className="bg-[#141417] border border-slate-800/80 rounded-2xl p-6 space-y-3 relative overflow-hidden group hover:border-slate-700 transition-all"
            >
              <div className="flex items-center justify-between">
                <span className="text-2xl font-black text-red-500/80 font-mono">
                  {item.step}
                </span>
                <div className="w-2 h-2 rounded-full bg-red-500/40 group-hover:bg-red-500 transition-colors" />
              </div>
              <h3 className="text-lg font-bold text-white">{item.title}</h3>
              <p className="text-xs sm:text-sm text-slate-400 leading-relaxed">
                {item.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Section 3: Benefits of PDF to Word Conversion */}
      <section className="space-y-8">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <span className="text-xs font-bold text-red-400 uppercase tracking-wider">
            Advantages
          </span>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-white">
            Key Benefits of Converting PDF to Word
          </h2>
          <p className="text-sm text-slate-400">
            Unlock complete document editability and streamline your writing workflow.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {[
            {
              icon: Edit3,
              title: 'Full Text Editability',
              desc: 'Modify text, correct typos, adjust styling, and reformat paragraphs freely in Microsoft Word.',
            },
            {
              icon: Scan,
              title: 'OCR for Scanned PDFs',
              desc: 'Transform paper scans, image documents, and photos into searchable, editable digital Word text.',
            },
            {
              icon: Award,
              title: 'Layout & Table Retention',
              desc: 'Preserves tables, image placements, margins, lists, and font typography accurately.',
            },
            {
              icon: ShieldCheck,
              title: 'Privacy & Security First',
              desc: 'Local browser processing ensures confidential financial, medical, and legal files stay protected.',
            },
            {
              icon: Zap,
              title: 'Fast Batch Conversion',
              desc: 'Convert dozens of PDF files simultaneously with multi-threaded processing and ZIP export.',
            },
            {
              icon: CheckCircle2,
              title: '100% Watermark-Free',
              desc: 'Export clean Word (.docx) files ready for executive presentations and academic submissions.',
            },
            {
              icon: Smartphone,
              title: 'Mobile-Optimized',
              desc: 'Convert PDF documents on iPhone, iPad, Android tablets, and mobile devices on the go.',
            },
            {
              icon: Globe,
              title: 'Universal Compatibility',
              desc: 'Generated DOCX files work seamlessly in Word, Google Docs, Pages, and LibreOffice.',
            },
          ].map((benefit, idx) => {
            const IconComponent = benefit.icon;
            return (
              <div
                key={idx}
                className="bg-[#141417]/80 border border-slate-800/80 rounded-2xl p-5 space-y-3 hover:border-slate-700 transition-all"
              >
                <div className="w-10 h-10 rounded-xl bg-red-500/10 text-red-400 border border-red-500/20 flex items-center justify-center">
                  <IconComponent className="w-5 h-5" />
                </div>
                <h3 className="text-base font-bold text-white">{benefit.title}</h3>
                <p className="text-xs text-slate-400 leading-relaxed">{benefit.desc}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* Section 4: Why Choose SmartPDF AI */}
      <section className="bg-gradient-to-br from-[#141417] via-slate-900 to-[#141417] border border-slate-800/80 rounded-3xl p-6 sm:p-10 space-y-6 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-red-600/5 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-3xl space-y-4">
          <span className="text-xs font-bold text-red-400 uppercase tracking-wider flex items-center gap-1.5">
            <Sparkles className="w-4 h-4 fill-red-400/20" />
            Why Choose SmartPDF AI?
          </span>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-white">
            High-Precision PDF to Word Conversion Engine
          </h2>
          <p className="text-sm sm:text-base text-slate-300 leading-relaxed">
            Most free online PDF to Word converters alter font spacing, break table structures, produce garbled character text, or mandate file uploads to untrusted servers. <strong>SmartPDF AI</strong> delivers superior document conversion through advanced structural layout analysis and client-side privacy.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
            {[
              'In-browser WebAssembly engine for maximum speed',
              'Integrated Optical Character Recognition (OCR)',
              'Accurate table, font, and layout preservation',
              'Unlimited batch conversions with ZIP download',
              'Zero watermarks, forced sign-ups, or hidden fees',
              'Compatible with Microsoft Word, Google Docs & Pages',
            ].map((feature, fIdx) => (
              <div key={fIdx} className="flex items-center space-x-2.5 text-xs sm:text-sm text-slate-200">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                <span>{feature}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Section 5: Frequently Asked Questions (9 FAQs) */}
      <section className="space-y-8">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <span className="text-xs font-bold text-red-400 uppercase tracking-wider flex items-center justify-center gap-1.5">
            <HelpCircle className="w-4 h-4" />
            Got Questions?
          </span>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-white">
            Frequently Asked Questions
          </h2>
          <p className="text-sm text-slate-400">
            Find quick answers to common questions about converting PDF files to editable Word documents.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="bg-[#141417]/90 border border-slate-800/80 rounded-2xl p-6 space-y-2 hover:border-slate-700 transition-all"
            >
              <h3 className="text-base font-bold text-white flex items-start gap-2">
                <span className="text-red-400 text-xs font-mono mt-1 shrink-0">
                  Q{index + 1}.
                </span>
                <span>{faq.question}</span>
              </h3>
              <p className="text-xs sm:text-sm text-slate-400 leading-relaxed pl-6 border-l-2 border-red-500/30">
                {faq.answer}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Section 6: Internal Links */}
      <section className="bg-[#141417]/80 border border-slate-800/80 rounded-3xl p-6 sm:p-8 space-y-6">
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div>
            <span className="text-xs font-bold text-red-400 uppercase tracking-wider">
              Ecosystem
            </span>
            <h2 className="text-xl sm:text-2xl font-bold text-white">
              Explore More Free PDF Tools
            </h2>
          </div>
          <Link
            to="/blog"
            className="text-xs text-red-400 hover:text-red-300 font-semibold flex items-center space-x-1"
          >
            <span>Visit Blog</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <Link
            to="/merge-pdf"
            className="group bg-slate-900/90 border border-slate-800 hover:border-red-500/50 rounded-2xl p-5 transition-all space-y-2 block"
          >
            <div className="w-9 h-9 rounded-xl bg-red-500/10 text-red-400 border border-red-500/20 flex items-center justify-center group-hover:scale-105 transition-transform">
              <Layers className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-bold text-white group-hover:text-red-400 transition-colors flex items-center justify-between">
              <span>Merge PDF</span>
              <ArrowRight className="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-opacity" />
            </h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Combine multiple PDF files into one continuous document easily.
            </p>
          </Link>

          <Link
            to="/compress-pdf"
            className="group bg-slate-900/90 border border-slate-800 hover:border-red-500/50 rounded-2xl p-5 transition-all space-y-2 block"
          >
            <div className="w-9 h-9 rounded-xl bg-red-500/10 text-red-400 border border-red-500/20 flex items-center justify-center group-hover:scale-105 transition-transform">
              <Minimize2 className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-bold text-white group-hover:text-red-400 transition-colors flex items-center justify-between">
              <span>Compress PDF</span>
              <ArrowRight className="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-opacity" />
            </h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Reduce PDF file size for easy email attachments without quality loss.
            </p>
          </Link>

          <Link
            to="/split-pdf"
            className="group bg-slate-900/90 border border-slate-800 hover:border-red-500/50 rounded-2xl p-5 transition-all space-y-2 block"
          >
            <div className="w-9 h-9 rounded-xl bg-red-500/10 text-red-400 border border-red-500/20 flex items-center justify-center group-hover:scale-105 transition-transform">
              <Scissors className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-bold text-white group-hover:text-red-400 transition-colors flex items-center justify-between">
              <span>Split PDF</span>
              <ArrowRight className="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-opacity" />
            </h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Extract specific pages or separate large PDF files into individual files.
            </p>
          </Link>

          <Link
            to="/blog"
            className="group bg-slate-900/90 border border-slate-800 hover:border-red-500/50 rounded-2xl p-5 transition-all space-y-2 block"
          >
            <div className="w-9 h-9 rounded-xl bg-red-500/10 text-red-400 border border-red-500/20 flex items-center justify-center group-hover:scale-105 transition-transform">
              <BookOpen className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-bold text-white group-hover:text-red-400 transition-colors flex items-center justify-between">
              <span>SmartPDF Blog</span>
              <ArrowRight className="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-opacity" />
            </h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Read step-by-step tutorials, document tips, and workflow best practices.
            </p>
          </Link>
        </div>
      </section>
    </div>
  );
};
