import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  FileType,
  FileText,
  Layers,
  Minimize2,
  Scissors,
  BookOpen,
  CheckCircle2,
  ShieldCheck,
  Zap,
  HelpCircle,
  Sparkles,
  ArrowRight,
  Edit3,
  Globe,
  Smartphone,
  Cpu,
  Lock,
  Award,
  ChevronDown,
} from 'lucide-react';
import { RecommendedArticles } from './RecommendedArticles';
import { RelatedTools } from './RelatedTools';

export const WordToPDFSEOContent: React.FC = () => {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [showFullGuide, setShowFullGuide] = useState(false);

  const faqs = [
    {
      question: 'Is it safe to convert Word documents to PDF on SmartPDF AI?',
      answer:
        'Yes, 100% secure. SmartPDF AI converts Word (.docx, .doc, .odt) documents with zero persistent storage. Your files are processed securely in memory and discarded immediately after generation.',
    },
    {
      question: 'Will converting Word to PDF preserve my fonts, formatting, and tables?',
      answer:
        'Yes! SmartPDF AI uses a high-fidelity rendering engine that preserves custom typography, table grids, headers, footers, margins, embedded graphics, and vector shapes with 100% accuracy.',
    },
    {
      question: 'Can I convert old .doc or OpenOffice .odt files?',
      answer:
        'Yes. We support all major Word document formats including Microsoft Word DOCX (.docx), legacy DOC (.doc), and OpenDocument Text (.odt).',
    },
    {
      question: 'Is there a limit on file size or page count?',
      answer:
        'SmartPDF AI allows conversions for documents up to 50MB with unlimited page counts and no daily usage restrictions.',
    },
    {
      question: 'Does SmartPDF AI add watermarks to converted PDF files?',
      answer:
        'Never. Every PDF generated by SmartPDF AI is clean, professional, and completely free of watermarks or promotional branding.',
    },
    {
      question: 'Does the Word to PDF converter work on mobile phones and tablets?',
      answer:
        'Yes! SmartPDF AI is fully responsive and optimized to run seamlessly across iPhone, iPad, Android devices, macOS, Windows, and Linux browsers.',
    },
  ];

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  };

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  return (
    <div className="mt-12 border-t border-slate-800/80 pt-10 space-y-10 text-slate-300">
      {/* FAQ Schema Script for Search Engines */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      {/* Feature Highlights Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5">
        {[
          {
            icon: Award,
            title: '100% Layout Fidelity',
            desc: 'Preserves fonts, tables, margins & graphics perfectly',
          },
          {
            icon: ShieldCheck,
            title: 'Secure & Private',
            desc: 'Zero file storage — processed in memory',
          },
          {
            icon: Zap,
            title: 'Auto-Download',
            desc: 'Instant conversion with automatic file delivery',
          },
          {
            icon: CheckCircle2,
            title: 'Watermark-Free',
            desc: 'Clean, publication-ready PDF output',
          },
        ].map((feat, idx) => {
          const Icon = feat.icon;
          return (
            <div
              key={idx}
              className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 hover:border-white/10 transition-all flex flex-col justify-between"
            >
              <div className="w-8 h-8 rounded-xl bg-red-500/10 text-red-400 border border-red-500/20 flex items-center justify-center mb-2.5">
                <Icon className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-xs sm:text-sm font-bold text-white mb-0.5">{feat.title}</h3>
                <p className="text-[11px] text-slate-400 leading-snug">{feat.desc}</p>
              </div>
            </div>
          );
        })}
      </div>

      {/* Compact Interactive FAQ Hub */}
      <section className="bg-[#12131F]/90 border border-white/10 rounded-[28px] p-6 sm:p-8 shadow-2xl space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-white/10 pb-4">
          <div>
            <span className="text-[11px] font-bold text-red-400 uppercase tracking-wider flex items-center gap-1.5">
              <HelpCircle className="w-3.5 h-3.5" />
              FAQ & Information
            </span>
            <h2 className="text-lg sm:text-xl font-black text-white mt-0.5">
              Frequently Asked Questions
            </h2>
          </div>
          <span className="text-xs text-slate-400">{faqs.length} answers available</span>
        </div>

        {/* FAQ Accordion List */}
        <div className="space-y-2.5">
          {faqs.map((faq, index) => {
            const isOpen = openFaq === index;
            return (
              <div
                key={index}
                className="rounded-2xl bg-white/[0.02] border border-white/5 overflow-hidden transition-all hover:border-white/10"
              >
                <button
                  type="button"
                  onClick={() => toggleFaq(index)}
                  className="w-full p-4 text-left flex items-center justify-between gap-4 cursor-pointer"
                  aria-expanded={isOpen}
                >
                  <span className="text-xs sm:text-sm font-bold text-slate-200 hover:text-white transition-colors">
                    {faq.question}
                  </span>
                  <ChevronDown
                    className={`w-4 h-4 text-slate-400 shrink-0 transition-transform duration-200 ${
                      isOpen ? 'rotate-180 text-red-400' : ''
                    }`}
                  />
                </button>

                {isOpen && (
                  <div className="px-4 pb-4 pt-1 text-xs sm:text-sm text-slate-400 leading-relaxed border-t border-white/5">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* Collapsible Comprehensive Guide (Preserves 100% SEO Keywords & Depth) */}
      <section className="bg-[#12131F]/80 border border-white/10 rounded-[28px] p-6 sm:p-8 space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-red-500/10 text-red-400 border border-red-500/20">
              <FileType className="w-5 h-5" />
            </div>
            <div>
              <span className="text-[11px] font-semibold text-red-400 uppercase tracking-wider">
                User Guide & Specifications
              </span>
              <h2 className="text-base sm:text-lg font-extrabold text-white">
                Word to PDF Conversion Guide
              </h2>
            </div>
          </div>

          <button
            type="button"
            onClick={() => setShowFullGuide(!showFullGuide)}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white/[0.06] hover:bg-white/[0.12] border border-white/10 text-xs font-semibold text-slate-300 hover:text-white transition-all cursor-pointer w-fit"
          >
            <span>{showFullGuide ? 'Hide Guide' : 'Read Full Guide'}</span>
            <ChevronDown
              className={`w-3.5 h-3.5 transition-transform ${showFullGuide ? 'rotate-180' : ''}`}
            />
          </button>
        </div>

        {/* Step-by-step summary */}
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 pt-2">
          {[
            { step: '01', title: 'Select Word File', desc: 'DOCX, DOC, or ODT files' },
            { step: '02', title: 'Initialize Engine', desc: 'High-fidelity layout parsing' },
            { step: '03', title: 'Convert', desc: 'Preserves fonts & vector graphics' },
            { step: '04', title: 'Auto-Download', desc: 'Get your PDF instantly' },
          ].map((item) => (
            <div key={item.step} className="p-3.5 rounded-xl bg-white/[0.02] border border-white/5">
              <span className="text-red-400 font-mono font-bold text-xs">{item.step}</span>
              <h4 className="text-xs font-bold text-white mt-1">{item.title}</h4>
              <p className="text-[11px] text-slate-400 mt-0.5">{item.desc}</p>
            </div>
          ))}
        </div>

        {/* Expandable Technical Text */}
        {showFullGuide && (
          <div className="space-y-6 pt-4 border-t border-white/5 text-xs sm:text-sm leading-relaxed text-slate-300">
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white">Why Convert Word to PDF?</h3>
              <p>
                Converting Word (.docx, .doc) files into PDF creates a universally compatible, read-only document that renders identically across any computer, smartphone, or operating system. It locks in font formatting, page breaks, margins, and graphics, preventing accidental edits or layout shifts.
              </p>
            </div>

            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white">Why Choose SmartPDF AI Word to PDF?</h3>
              <p>
                SmartPDF AI utilizes an advanced conversion pipeline that accurately renders OpenXML documents into PDF format without quality degradation or watermark branding.
              </p>
            </div>
          </div>
        )}
      </section>

      {/* Recommended Articles Section */}
      <RecommendedArticles category="Format Conversion" limit={3} />

      {/* Related Tools Section */}
      <RelatedTools currentToolPath="/word-to-pdf" limit={4} />
    </div>
  );
};
