import { PDFTool } from '../types/toolTypes';

export const PDF_TOOLS: PDFTool[] = [
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one unified document easily in seconds.',
    icon: 'Layers',
    category: 'organize',
    path: '/merge',
    popular: true,
    badge: 'Popular',
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate one PDF page range or extract all pages into independent files.',
    icon: 'Scissors',
    category: 'organize',
    path: '/split',
    popular: true,
    badge: 'Popular',
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size of your PDF while maintaining optimal quality.',
    icon: 'Minimize2',
    category: 'edit',
    path: '/compress',
    popular: true,
    badge: 'Popular',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF files into editable DOCX Word documents seamlessly.',
    icon: 'FileText',
    category: 'convert',
    path: '/pdf-to-word',
    popular: true,
    badge: 'Popular',
    color: 'from-blue-600 to-cyan-600',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Microsoft Word DOC and DOCX files to PDF documents quickly.',
    icon: 'FileType',
    category: 'convert',
    path: '/word-to-pdf',
    popular: true,
    color: 'from-sky-500 to-blue-700',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages 90, 180 or 270 degrees clockwise or counterclockwise.',
    icon: 'RotateCw',
    category: 'organize',
    path: '/rotate',
    popular: true,
    color: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    description: 'Add custom text watermarks across pages for security and branding.',
    icon: 'Stamp',
    category: 'security',
    path: '/watermark',
    color: 'from-pink-500 to-rose-600',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Add page numbers with custom positions, styling, and starting values.',
    icon: 'Hash',
    category: 'edit',
    path: '/page-numbers',
    color: 'from-violet-500 to-purple-700',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Extract and convert scanned PDF pages into selectable, searchable text or editable files.',
    icon: 'ScanText',
    category: 'convert',
    path: '/ocr-pdf',
    popular: true,
    badge: 'AI OCR',
    color: 'from-amber-500 to-red-600',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt PDF with passwords and set printing, copying, editing, and annotating permissions.',
    icon: 'Lock',
    category: 'security',
    path: '/protect-pdf',
    popular: true,
    badge: 'Security',
    color: 'from-emerald-500 to-teal-700',
  },
  {
    id: 'ai-chat',
    name: 'AI Document Chat',
    description: 'Ask questions, extract page references, and converse with your PDF using Gemini AI.',
    icon: 'MessageSquare',
    category: 'ai',
    path: '/ai-chat',
    popular: true,
    badge: 'Gemini AI',
    color: 'from-red-500 to-amber-600',
  },
  {
    id: 'ai-assistant',
    name: 'AI Document Assistant',
    description: 'Summarize, rewrite, translate, extract tables, and generate flashcards from PDFs.',
    icon: 'Sparkles',
    category: 'ai',
    path: '/ai-assistant',
    popular: true,
    badge: 'Gemini AI',
    color: 'from-purple-500 to-pink-600',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert JPG, PNG, WebP, or SVG images into a compiled PDF document easily.',
    icon: 'Image',
    category: 'image',
    path: '/image-to-pdf',
    popular: true,
    badge: 'Image Tool',
    color: 'from-emerald-500 to-cyan-600',
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Extract PDF pages into high-resolution PNG or JPG image files in seconds.',
    icon: 'FileImage',
    category: 'image',
    path: '/pdf-to-image',
    popular: true,
    badge: 'Image Tool',
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'compress-image',
    name: 'Compress Image',
    description: 'Reduce JPG, PNG, and WebP image size while preserving visual quality.',
    icon: 'Minimize2',
    category: 'image',
    path: '/compress-image',
    popular: true,
    badge: 'Image Tool',
    color: 'from-amber-500 to-rose-600',
  },
  {
    id: 'resize-image',
    name: 'Resize Image',
    description: 'Change image dimensions, width, height, and format with aspect ratio controls.',
    icon: 'Scaling',
    category: 'image',
    path: '/resize-image',
    popular: true,
    badge: 'Image Tool',
    color: 'from-violet-500 to-pink-600',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection and permissions security from locked PDF files.',
    icon: 'Unlock',
    category: 'security',
    path: '/unlock-pdf',
    popular: true,
    badge: 'Security',
    color: 'from-red-500 to-rose-700',
  },
];
