import { PDFTool } from '../types/toolTypes';

export const PDF_TOOLS: PDFTool[] = [
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one unified document easily in seconds.',
    icon: 'Layers',
    category: 'organize',
    path: '/merge',
    popular: true,
    badge: 'Popular',
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate one PDF page range or extract all pages into independent files.',
    icon: 'Scissors',
    category: 'organize',
    path: '/split',
    popular: true,
    badge: 'Popular',
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'delete-pages',
    name: 'Delete PDF Pages',
    description: 'Remove unwanted pages from your PDF file while preserving quality and metadata.',
    icon: 'Trash2',
    category: 'organize',
    path: '/delete-pages',
    popular: true,
    badge: 'Essentials',
    color: 'from-rose-600 to-red-700',
  },
  {
    id: 'extract-pages',
    name: 'Extract PDF Pages',
    description: 'Extract specific single pages or page ranges into a brand new PDF document.',
    icon: 'FileOutput',
    category: 'organize',
    path: '/extract-pages',
    popular: true,
    badge: 'Essentials',
    color: 'from-violet-600 to-purple-700',
  },
  {
    id: 'rearrange-pages',
    name: 'Rearrange PDF Pages',
    description: 'Reorder, move, and drag-and-drop pages of your PDF document visually.',
    icon: 'ArrowUpDown',
    category: 'organize',
    path: '/rearrange-pages',
    popular: true,
    badge: 'Essentials',
    color: 'from-blue-600 to-cyan-600',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size of your PDF while maintaining optimal quality.',
    icon: 'Minimize2',
    category: 'edit',
    path: '/compress',
    popular: true,
    badge: 'Popular',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF files into editable DOCX Word documents seamlessly.',
    icon: 'FileText',
    category: 'convert',
    path: '/pdf-to-word',
    popular: true,
    badge: 'Popular',
    color: 'from-blue-600 to-cyan-600',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Microsoft Word DOC and DOCX files to PDF documents quickly.',
    icon: 'FileType',
    category: 'convert',
    path: '/word-to-pdf',
    popular: true,
    color: 'from-sky-500 to-blue-700',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel workbooks (.xlsx, .xls) and CSV spreadsheets into formatted PDF tables.',
    icon: 'FileSpreadsheet',
    category: 'convert',
    path: '/excel-to-pdf-tool',
    popular: true,
    badge: 'Spreadsheet',
    color: 'from-emerald-600 to-teal-700',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract PDF tables and structured document data into editable Excel workbooks.',
    icon: 'Table',
    category: 'convert',
    path: '/pdf-to-excel',
    popular: true,
    badge: 'Extract',
    color: 'from-teal-600 to-emerald-700',
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PowerPoint slide decks (.pptx) into printable PDF documents.',
    icon: 'Presentation',
    category: 'convert',
    path: '/powerpoint-to-pdf',
    popular: true,
    badge: 'Slides',
    color: 'from-orange-600 to-amber-700',
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF document pages into an editable PowerPoint presentation.',
    icon: 'Presentation',
    category: 'convert',
    path: '/pdf-to-powerpoint',
    popular: true,
    badge: 'Presentation',
    color: 'from-amber-600 to-orange-700',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages 90, 180 or 270 degrees clockwise or counterclockwise.',
    icon: 'RotateCw',
    category: 'organize',
    path: '/rotate',
    popular: true,
    color: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    description: 'Add custom text watermarks across pages for security and branding.',
    icon: 'Stamp',
    category: 'security',
    path: '/watermark',
    color: 'from-pink-500 to-rose-600',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Add page numbers with custom positions, styling, and starting values.',
    icon: 'Hash',
    category: 'edit',
    path: '/page-numbers',
    color: 'from-violet-500 to-purple-700',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Extract and convert scanned PDF pages into selectable, searchable text or editable files.',
    icon: 'ScanText',
    category: 'convert',
    path: '/ocr-pdf',
    popular: true,
    badge: 'AI OCR',
    color: 'from-amber-500 to-red-600',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt PDF with passwords and set printing, copying, editing, and annotating permissions.',
    icon: 'Lock',
    category: 'security',
    path: '/protect-pdf',
    popular: true,
    badge: 'Security',
    color: 'from-emerald-500 to-teal-700',
  },
  {
    id: 'ai-chat',
    name: 'AI Document Chat',
    description: 'Ask questions, extract page references, and converse with your PDF using Gemini AI.',
    icon: 'MessageSquare',
    category: 'ai',
    path: '/ai-chat',
    popular: true,
    badge: 'Gemini AI',
    color: 'from-red-500 to-amber-600',
  },
  {
    id: 'ai-assistant',
    name: 'AI Document Assistant',
    description: 'Summarize, rewrite, translate, extract tables, and generate flashcards from PDFs.',
    icon: 'Sparkles',
    category: 'ai',
    path: '/ai-assistant',
    popular: true,
    badge: 'Gemini AI',
    color: 'from-purple-500 to-pink-600',
  },
  {
    id: 'document-analyzer',
    name: 'Document Analyzer',
    description: 'Autonomous document audit, entity extraction, risk discovery, and compliance reports.',
    icon: 'ScanText',
    category: 'ai',
    path: '/document-analyzer',
    popular: true,
    badge: 'AI Audit',
    color: 'from-rose-500 to-red-600',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert JPG, PNG, WebP, or SVG images into a compiled PDF document easily.',
    icon: 'Image',
    category: 'convert',
    path: '/image-to-pdf',
    popular: true,
    badge: 'Convert',
    color: 'from-emerald-500 to-cyan-600',
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Extract PDF pages into high-resolution PNG or JPG image files in seconds.',
    icon: 'FileImage',
    category: 'convert',
    path: '/pdf-to-image',
    popular: true,
    badge: 'Convert',
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection and permissions security from locked PDF files.',
    icon: 'Unlock',
    category: 'security',
    path: '/unlock-pdf',
    popular: true,
    badge: 'Security',
    color: 'from-red-500 to-rose-700',
  },
  {
    id: 'diff-compare',
    name: 'AI PDF Comparison',
    description: 'Compare contracts and document revisions side-by-side with neural visual diff and clause audit.',
    icon: 'GitCompare',
    category: 'ai',
    path: '/diff-compare',
    popular: true,
    badge: 'Diff AI',
    color: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'resume-reviewer',
    name: 'AI Resume & ATS Reviewer',
    description: 'Calculate ATS scoring, uncover missing keywords, and generate high-impact quantified CV bullet rewrites.',
    icon: 'FileCheck',
    category: 'ai',
    path: '/resume-reviewer',
    popular: true,
    badge: 'ATS Score',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'pii-redaction',
    name: 'Smart PII Redaction',
    description: 'Autonomous privacy scan for NID, emails, phone numbers, and financial data with coordinate redaction.',
    icon: 'EyeOff',
    category: 'security',
    path: '/pii-redaction',
    popular: true,
    badge: 'Privacy Shield',
    color: 'from-rose-500 to-red-600',
  },
  {
    id: 'flashcard-quiz',
    name: 'AI Flashcard & Quiz Studio',
    description: 'Transform PDFs into 3D interactive flashcards and active-recall multiple choice practice exams.',
    icon: 'GraduationCap',
    category: 'ai',
    path: '/flashcard-quiz',
    popular: true,
    badge: 'Study AI',
    color: 'from-indigo-500 to-purple-600',
  },
  {
    id: 'audio-podcast',
    name: 'AI Audio PDF & Podcast',
    description: 'Convert heavy PDF articles and whitepapers into natural spoken audio digests and podcast episodes.',
    icon: 'Headphones',
    category: 'ai',
    path: '/audio-podcast',
    popular: true,
    badge: 'Voice AI',
    color: 'from-cyan-500 to-teal-600',
  },
  {
    id: 'invoice-processor',
    name: 'AI Invoice & Form Processor',
    description: 'Extract line-items, tax breakdowns, vendor details, and structured tabular data to CSV/Excel format.',
    icon: 'Receipt',
    category: 'ai',
    path: '/invoice-processor',
    popular: true,
    badge: 'Table AI',
    color: 'from-amber-500 to-orange-600',
  },
];
